repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      # Run the linter with specific rule selection (I = import-related rules) and auto-fix.
      - id: ruff
        name: ruff-import-sort
        args: [check, --select, I, --fix]

      # Run the full auto-formatter.
      - id: ruff-format
        name: ruff-code-format
